var annotated =
[
    [ "AlphaBetaFilter< T >", "class_alpha_beta_filter.html", "class_alpha_beta_filter" ],
    [ "Attack3Joystick", "class_attack3_joystick.html", "class_attack3_joystick" ],
    [ "AutonomousCommand", "class_autonomous_command.html", "class_autonomous_command" ],
    [ "CommandBase", "class_command_base.html", "class_command_base" ],
    [ "DisableEncoders", "class_disable_encoders.html", "class_disable_encoders" ],
    [ "DisableGyro", "class_disable_gyro.html", "class_disable_gyro" ],
    [ "DriveSubsystem", "class_drive_subsystem.html", "class_drive_subsystem" ],
    [ "DriveTo", "class_drive_to.html", "class_drive_to" ],
    [ "DriveToAngle", "class_drive_to_angle.html", "class_drive_to_angle" ],
    [ "DriveToRelativeAngle", "class_drive_to_relative_angle.html", "class_drive_to_relative_angle" ],
    [ "DriveWithJoystick", "class_drive_with_joystick.html", "class_drive_with_joystick" ],
    [ "ElevateShooter", "class_elevate_shooter.html", "class_elevate_shooter" ],
    [ "ElevateShooterRelative", "class_elevate_shooter_relative.html", "class_elevate_shooter_relative" ],
    [ "ElevateShooterWithJoystick", "class_elevate_shooter_with_joystick.html", "class_elevate_shooter_with_joystick" ],
    [ "EnableEncoders", "class_enable_encoders.html", "class_enable_encoders" ],
    [ "EnableGyro", "class_enable_gyro.html", "class_enable_gyro" ],
    [ "FlickFrisbee", "class_flick_frisbee.html", "class_flick_frisbee" ],
    [ "FRCXboxJoystick", "class_f_r_c_xbox_joystick.html", "class_f_r_c_xbox_joystick" ],
    [ "GyroSubsystem", "class_gyro_subsystem.html", "class_gyro_subsystem" ],
    [ "LogFile", "class_log_file.html", "class_log_file" ],
    [ "LogPOT", "class_log_p_o_t.html", "class_log_p_o_t" ],
    [ "LogSystem", "class_log_system.html", "class_log_system" ],
    [ "NorthernForceRobot", "class_northern_force_robot.html", null ],
    [ "OI", "class_o_i.html", "class_o_i" ],
    [ "PrepareShooter", "class_prepare_shooter.html", "class_prepare_shooter" ],
    [ "RampedCANJaguar", "class_ramped_c_a_n_jaguar.html", "class_ramped_c_a_n_jaguar" ],
    [ "RobotNav", "class_robot_nav.html", "class_robot_nav" ],
    [ "RobotPosition", "struct_robot_position.html", "struct_robot_position" ],
    [ "SetDrivePID", "class_set_drive_p_i_d.html", "class_set_drive_p_i_d" ],
    [ "ShooterElevatorSubsystem", "class_shooter_elevator_subsystem.html", "class_shooter_elevator_subsystem" ],
    [ "ShooterSubsystem", "class_shooter_subsystem.html", "class_shooter_subsystem" ],
    [ "SocketClient", "class_socket_client.html", "class_socket_client" ],
    [ "SpinupShooter", "class_spinup_shooter.html", "class_spinup_shooter" ],
    [ "SpinupShooterAuto", "class_spinup_shooter_auto.html", "class_spinup_shooter_auto" ],
    [ "SpinupShooterWithJoystick", "class_spinup_shooter_with_joystick.html", "class_spinup_shooter_with_joystick" ],
    [ "Target", "struct_target.html", "struct_target" ],
    [ "UpdateNav", "class_update_nav.html", "class_update_nav" ],
    [ "Vector2D", "class_vector2_d.html", "class_vector2_d" ],
    [ "Vector3D", "class_vector3_d.html", "class_vector3_d" ]
];