var hierarchy =
[
    [ "AlphaBetaFilter< T >", "class_alpha_beta_filter.html", null ],
    [ "Attack3Joystick", "class_attack3_joystick.html", null ],
    [ "AutonomousCommand", "class_autonomous_command.html", null ],
    [ "CommandBase", "class_command_base.html", [
      [ "DisableEncoders", "class_disable_encoders.html", null ],
      [ "DisableGyro", "class_disable_gyro.html", null ],
      [ "DriveTo", "class_drive_to.html", null ],
      [ "DriveToAngle", "class_drive_to_angle.html", null ],
      [ "DriveToRelativeAngle", "class_drive_to_relative_angle.html", null ],
      [ "DriveWithJoystick", "class_drive_with_joystick.html", null ],
      [ "ElevateShooter", "class_elevate_shooter.html", null ],
      [ "ElevateShooterRelative", "class_elevate_shooter_relative.html", null ],
      [ "ElevateShooterWithJoystick", "class_elevate_shooter_with_joystick.html", null ],
      [ "EnableEncoders", "class_enable_encoders.html", null ],
      [ "EnableGyro", "class_enable_gyro.html", null ],
      [ "FlickFrisbee", "class_flick_frisbee.html", null ],
      [ "LogPOT", "class_log_p_o_t.html", null ],
      [ "SetDrivePID", "class_set_drive_p_i_d.html", null ],
      [ "SpinupShooter", "class_spinup_shooter.html", null ],
      [ "SpinupShooterAuto", "class_spinup_shooter_auto.html", null ],
      [ "SpinupShooterWithJoystick", "class_spinup_shooter_with_joystick.html", null ],
      [ "UpdateNav", "class_update_nav.html", null ]
    ] ],
    [ "DriveSubsystem", "class_drive_subsystem.html", null ],
    [ "FRCXboxJoystick", "class_f_r_c_xbox_joystick.html", null ],
    [ "GyroSubsystem", "class_gyro_subsystem.html", null ],
    [ "LogFile", "class_log_file.html", null ],
    [ "LogSystem", "class_log_system.html", null ],
    [ "NorthernForceRobot", "class_northern_force_robot.html", null ],
    [ "OI", "class_o_i.html", null ],
    [ "PrepareShooter", "class_prepare_shooter.html", null ],
    [ "RampedCANJaguar", "class_ramped_c_a_n_jaguar.html", null ],
    [ "RobotNav", "class_robot_nav.html", null ],
    [ "RobotPosition", "struct_robot_position.html", null ],
    [ "ShooterElevatorSubsystem", "class_shooter_elevator_subsystem.html", null ],
    [ "ShooterSubsystem", "class_shooter_subsystem.html", null ],
    [ "SocketClient", "class_socket_client.html", null ],
    [ "Target", "struct_target.html", null ],
    [ "Vector2D", "class_vector2_d.html", null ],
    [ "Vector3D", "class_vector3_d.html", null ]
];